Getting the parent of a child
rmrk-team/rmrk-ink pull request #52
Opened 2023-03-12 14:44 UTC by Szegoo

2023-03-13 18:57 UTC, Szegoo commented
From my understanding, there is no way at the moment to iterate over a `Mapping` therefore I introduced a new mapping that will keep track of the parents of children. Also, would it be useful to track parents of pending children?

@Maar-io @ilionic

2023-03-17 13:06 UTC, Maar-io requested changes
We discussed previously that it is hard to track parent NFT, but in case of nesting, the parent-NFT-address is the owner of the child NFT.
And childNFT can have only one parent

2023-03-17 13:06 UTC, Maar-io commented on crates/nesting/src/lib.rs
> +            self.add_parent_to_child(&child_nft, &to_parent_token_id);
I think you are mixing parent and child.
The `add_child` is called on parent nft and adding this new mapping will not accomplish what you had in mind (in the PR description)

2023-03-17 13:06 UTC, Maar-io commented on crates/nesting/src/lib.rs
> +            self.add_parent_to_child(&child_nft, &to_parent_token_id);
And childNFT can have only one parent

2023-03-20 07:49 UTC, bobo-k2 commented
I like the idea, because this is the feature I am missing from current implementation. I agree with @Maar-io. Calling `add_chilld` is called on parent and you code will update `children_parent` mapping on parent. Also, please add some tests.

2023-04-05 18:14 UTC, Maar-io commented on crates/nesting/src/lib.rs
> +    pub owner_of: Mapping<ChildNft, Id>,
perhaps `parent_of` or similar would be better name since `owner_of` already exists in [psp34](https://github.com/727-Ventures/openbrush-contracts/blob/107348d75ba40d5abeee4978fd2c70ead0122d3b/contracts/src/token/psp34/psp34.rs#L98)

2023-04-05 18:16 UTC, Szegoo commented on crates/nesting/src/lib.rs
> +    pub owner_of: Mapping<ChildNft, Id>,
Makes sense, I will also rename the other functions I created to match this new name.

2023-04-07 11:56 UTC, Szegoo commented
@Maar-io @bobo-k2 It seems like calling any query from the `query.js` file in the integration tests results in the following error:
```
Error: the object {
  "issue": "OUTPUT_IS_NULL"
} was thrown, throw an Error :)
```
Should I test the new query with an integration test, seems like we are not testing any other queries.

2023-04-13 13:52 UTC, Szegoo commented
> Do you have an example of a query being called?

@boyswan You mean do I have an example of the get parent query being called, or? For me calling any query in the integration test results in the above-mentioned error. I am not sure if others are facing the same problem. This is the way I make the query: 
```rs
// code inside the nesting integration test.
// -- snip --
const _ = await child.query.getParentOfChild([child.address, { u64: 1}]);
// ^^^^ Making this call results in an error.
// -- snip --
```

2023-04-14 06:40 UTC, bobo-k2 commented
> "OUT

@Szegoo Mario and I debugged similar issue last week. Maybe I can help to find root cause of the problem
Open `rmrk-ink/node_modules/@727-ventures/typechain-types/dist/src/query.js` and set breakpoint in line 203
<img width="601" alt="image" src="https://user-images.githubusercontent.com/8452361/231962404-084d163f-d810-4dec-ad2a-29fb7c588a7c.png">
Run test in debug mode and when breakpoint is reached type something like (I am writing this from top of my head so It may not work at first)
`console.log(result.asErr.registry.findMetaError(result.asErr.asModule);`

2023-04-14 08:32 UTC, boyswan commented
I did some digging and it seems like the issue lies with how the query functions call their storage (was using `MintingRef` as a way to call internal storage instead of directly accessing it). 

It looks like this behaviour has broken since ink 4.0, which will require some changes to how the Query trait works. We can make a separate issue/PR for this, as it's out of the scope of this feature!

2023-04-14 20:18 UTC, Szegoo commented
After running in debug mode and some logging I got the following error message:
```
A call tried to invoke a contract that is flagged as non-reentrant.
```
https://github.com/paritytech/substrate/blob/3f8dc9ed594fdba455d0bf6780768e7176188514/frame/contracts/src/lib.rs#L829-L832
Seems to me that @boyswan was correct.

2023-04-15 17:00 UTC, boyswan commented
Ahh of course - makes total sense now! So all we need to do is allow reentrancy for these calls. For example:

```rust
let parent_collection = PSP34Ref::owner_of_builder(&child_collection, child_id)
    .call_flags(ink::env::CallFlags::default().set_allow_reentry(true))
    .try_invoke();
```

2023-04-15 17:39 UTC, Szegoo commented
Oh, I got a bit confused, but I understand now :)

2023-04-17 18:17 UTC, boyswan approved these changes
With clone fix, LGTM

2023-04-17 18:17 UTC, boyswan commented on crates/rmrk/src/query.rs
> +        let child_id = child_nft.clone().1;
Minor thing here, but you're unnecessarily cloning the tuple all of its contents twice. Instead you can

```rust
let child_collection = child_nft.0;
let child_id = child_nft.1.clone();
```

2023-04-21 15:42 UTC, Maar-io approved these changes
LGTM

2023-04-22 13:17 UTC, merged