Cross contract check when equipping
rmrk-team/rmrk-ink pull request #71
Opened 2023-05-02 17:14 UTC by Szegoo

This PR adds the following:

- [X] Makes cross contract call in equip() function to call `ensure_token_can_be_equipped_with_asset_into_slot()`. To make this work I made the `ensure_token_can_be_equipped_with_asset_into_slot` part of the `equippable` trait and moved the implementation of it to `lib.rs`.
- [X] Introduce missing e2e test to cover equip. These tests are placed in the `merged_equippable.spec.ts` file. The `merged_equippable.spec.ts` file is now renamed to `equip.spec.ts` since it now covers all of the equipping functionality. This integration test introduces a new example with an avatar and sword contract which is somewhat similar to the `MergedEquippable` user story. Through this example, the equipping and unequipping functionality are tested.

AFAIK there are no unit tests that cover this functionality, hence there is nothing to be updated.

Closes: #33

2023-05-05 17:01 UTC, Szegoo commented on tests/equip.spec.ts
> +    it("Equip/Unequip works", async () => {
```suggestion
    it("Equip works", async () => {
```
This only tests equip functionality, should I also add tests for unequip in this PR or should that be done separately?

2023-05-07 10:28 UTC, boyswan commented on crates/equippable/src/lib.rs
> +        _part_slot_id: PartId,
I think the part_slot id still required as part of the logic [as in the evm spec](https://github.com/rmrk-team/evm/blob/master/contracts/RMRK/equippable/RMRKExternalEquip.sol#L486). Will get clarification on this.

2023-05-07 20:24 UTC, boyswan commented on crates/equippable/src/lib.rs
> +        _part_slot_id: PartId,
Ahh looks like you just need to equality check the `part_slot_id`.

```rust
if self
      .data::<EquippableData>()
      .valid_parent_slot
      .get((asset.equippable_group_id, parent_address))
      .contains(&part_slot_id) 
{
      ...
}
```

2023-05-07 20:51 UTC, Szegoo commented on crates/equippable/src/lib.rs
> +        _part_slot_id: PartId,
Yep, seems we weren't even checking for the `part_id` here. Great observation.

2023-05-07 21:00 UTC, boyswan commented on crates/equippable/src/lib.rs
> +use crate::traits::EquippableRef;
This can be moved to the import below:

```
use traits::{
    Equippable,
    EquippableEvents,
    EquippableRef,
};
```

2023-05-07 21:29 UTC, boyswan commented on crates/equippable/src/lib.rs
> +        if part_id.is_some() && part_id == Some(part_slot_id) {
`part_id.is_some()` is redundant here

2023-05-07 21:39 UTC, Szegoo commented on crates/equippable/src/lib.rs
> +        if part_id.is_some() && part_id == Some(part_slot_id) {
Correct. I initially wanted to do: `part_id.is_some() && part_id.unwrap() == part_slot_id` but ended up doing it the other way and forgot to remove `part_id.is_some()`

2023-05-07 21:42 UTC, boyswan commented on crates/equippable/src/lib.rs
> +        Ok(())
This can be simplified by implicitly returning the condition instead of using`?` and returning `Ok`:

```rust
...
 let part_id = self
      .data::<EquippableData>()
      .valid_parent_slot
      .get((asset.equippable_group_id, parent_address));

  if part_id == Some(part_slot_id) {
      self.ensure_asset_accepted(&token_id, &asset_id)
  } else {
      Err(RmrkError::UnknownPart.into())
  }
}
```

2023-05-08 16:48 UTC, Maar-io commented
Integration test started to fail again. Can you take a look what is the problem now?

2023-05-08 16:49 UTC, Maar-io requested changes
Instead of adding new test file, can you integrate this test into existing one?
The tests need some reshuffle and adding new file will make it even more complicated.

2023-05-08 17:00 UTC, Szegoo commented
> Instead of adding new test file, can you integrate this test into existing one? The tests need some reshuffle and adding new file will make it even more complicated.

@Maar-io Ok, I will move the test into `merged_equippable.spec.ts`, but I think it would be a good idea to then rename this file to `equip.spec.ts`. What do you think about this?

2023-05-08 18:15 UTC, Szegoo commented
> Integration test started to fail again. Can you take a look what is the problem now?

@Maar-io The integration test failure is not caused by this PR, it is the same error as the one in the main branch. Locally everything works well for me.

2023-05-09 17:07 UTC, Maar-io commented
> > Integration test started to fail again. Can you take a look what is the problem now?
> 
> @Maar-io The integration test failure is not caused by this PR, it is the same error as the one in the main branch. Locally everything works well for me.

No problem, we can open new issue and fix the integration test in the main

2023-05-09 17:41 UTC, Szegoo commented
I have moved the test to `merged_equippable.spec.ts` and renamed the file to `equip.spec.ts`.

2023-05-10 09:46 UTC, boyswan approved these changes
LGTM

Before you merge can you squash your commits?

2023-05-10 09:46 UTC, boyswan approved these changes
LGTM

Before you merge can you squash your commits?

2023-05-10 13:07 UTC, Maar-io approved these changes
LGTM

2023-05-10 14:48 UTC, merged